### ISSUE TITLE
Błędy Kamila Cały

### ISSUE THREAD

**Issue by zblazejowska** [smolenkamil/News-HUB#1]
- strona jest nieskalowalna, nie dostosowuje się do różnych rozdzielczości strony, nie powinieneś  tego tak zostawiać to część tego zadania
- do czego służą przyciski po lewej stronie? Wyglądają spoko ale nie do końca pasują do naszego UI, a poza tym nie mamy swoich stron na social mediach. Trzeba to usunąć.

**Comment by Riserax** [comment]
- no racja, te przyciski po lewej stronie nie będą nam potrzebne, trzeba je usunąć
- strona była nieskalowalna, bo moim zadaniem było zrobić szablon strony; responsywność to było osobne zadanie
